// <auto-generated />
using System.Collections.Generic;
using DMRS.MedicineInfo.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DMRS.MedicineInfo.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DMRS.MedicineInfo.Api.Domain.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("DMRS.MedicineInfo.Api.Domain.Medicine", b =>
                {
                    b.Property<string>("RxCui")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Indications")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RxCui");

                    b.ToTable("Medicines");
                });

            modelBuilder.Entity("IngredientMedicine", b =>
                {
                    b.Property<int>("IngredientsId")
                        .HasColumnType("integer");

                    b.Property<string>("MedicinesRxCui")
                        .HasColumnType("text");

                    b.HasKey("IngredientsId", "MedicinesRxCui");

                    b.HasIndex("MedicinesRxCui");

                    b.ToTable("MedicineIngredients", (string)null);
                });

            modelBuilder.Entity("DMRS.MedicineInfo.Api.Domain.Medicine", b =>
                {
                    b.OwnsOne("DMRS.MedicineInfo.Api.Domain.DosingInfo", "Dosing", b1 =>
                        {
                            b1.Property<string>("MedicineRxCui")
                                .HasColumnType("text");

                            b1.Property<decimal>("MaxDailyMg")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("MaxSingleMg")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("WarningThreshold")
                                .HasColumnType("numeric");

                            b1.HasKey("MedicineRxCui");

                            b1.ToTable("Medicines");

                            b1.WithOwner()
                                .HasForeignKey("MedicineRxCui");
                        });

                    b.OwnsOne("DMRS.MedicineInfo.Api.Domain.SafetyInfo", "Safety", b1 =>
                        {
                            b1.Property<string>("MedicineRxCui")
                                .HasColumnType("text");

                            b1.Property<bool>("IsControlled")
                                .HasColumnType("boolean");

                            b1.Property<string>("PregnancyCategory")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("MedicineRxCui");

                            b1.ToTable("Medicines");

                            b1.WithOwner()
                                .HasForeignKey("MedicineRxCui");
                        });

                    b.Navigation("Dosing")
                        .IsRequired();

                    b.Navigation("Safety")
                        .IsRequired();
                });

            modelBuilder.Entity("IngredientMedicine", b =>
                {
                    b.HasOne("DMRS.MedicineInfo.Api.Domain.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DMRS.MedicineInfo.Api.Domain.Medicine", null)
                        .WithMany()
                        .HasForeignKey("MedicinesRxCui")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
