// <auto-generated />
using System;
using DMRS.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DMRS.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260517094748_AddCdsRuleLifecycle")]
    partial class AddCdsRuleLifecycle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DMRS.Api.Domain.ClinicalDecisionSupport.CdsRuleDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CardTemplateJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ExpressionJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("HasUnpublishedChanges")
                        .HasColumnType("boolean");

                    b.Property<string>("HookId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PublishedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("PublishedVersionId")
                        .HasColumnType("uuid");

                    b.Property<int?>("PublishedVersionNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PublishedVersionId");

                    b.HasIndex("HookId", "Status", "IsActive");

                    b.ToTable("CdsRuleDefinitions");
                });

            modelBuilder.Entity("DMRS.Api.Domain.ClinicalDecisionSupport.CdsRuleVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CardTemplateJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ExpressionJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("HookId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PublishedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("RuleDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HookId");

                    b.HasIndex("RuleDefinitionId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("CdsRuleVersions");
                });

            modelBuilder.Entity("DMRS.Api.Domain.ClinicalDecisionSupport.MedicineKnowledgeRecord", b =>
                {
                    b.Property<string>("RxCui")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IndicationCodesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("IndicationSearchText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IngredientCodesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("IngredientNamesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("IngredientSearchText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("IsControlled")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MaxDailyMg")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MaxSingleMg")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PregnancyCategory")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("WarningThresholdMg")
                        .HasColumnType("numeric");

                    b.HasKey("RxCui");

                    b.HasIndex("Name");

                    b.ToTable("MedicineKnowledgeRecords");
                });

            modelBuilder.Entity("DMRS.Api.Domain.FhirResource", b =>
                {
                    b.Property<string>("ResourceType")
                        .HasColumnType("text");

                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VersionId")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("ResourceType", "Id");

                    b.ToTable("FhirResources");
                });

            modelBuilder.Entity("DMRS.Api.Domain.FhirResourceVersion", b =>
                {
                    b.Property<string>("ResourceType")
                        .HasColumnType("text");

                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("VersionId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ResourceType", "Id", "VersionId");

                    b.ToTable("FhirResourceVersions");
                });

            modelBuilder.Entity("DMRS.Api.Domain.ResourceIndex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SearchParamCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ResourceType", "SearchParamCode", "Value");

                    b.ToTable("ResourceIndices");
                });

            modelBuilder.Entity("DMRS.Api.Domain.ClinicalDecisionSupport.CdsRuleDefinition", b =>
                {
                    b.HasOne("DMRS.Api.Domain.ClinicalDecisionSupport.CdsRuleVersion", null)
                        .WithMany()
                        .HasForeignKey("PublishedVersionId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("DMRS.Api.Domain.ClinicalDecisionSupport.CdsRuleVersion", b =>
                {
                    b.HasOne("DMRS.Api.Domain.ClinicalDecisionSupport.CdsRuleDefinition", null)
                        .WithMany()
                        .HasForeignKey("RuleDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
